update lda-test evaluate-harp

diff --git a/bin/lda-test b/bin/lda-test
--- a/bin/lda-test
+++ b/bin/lda-test
@@ -4,81 +4,146 @@
 homedir=`dirname $0`
 homedir=`dirname $homedir`
 
-# dataset
-# enwiki-100k
-datadir=$homedir/data/enwiki-100k
-gibbsdict=$datadir/enwiki-100k-gibbs.wordids
-harpdict=$datadir/enwiki-100k-reid.wordids
-testset=$datadir/test100k.mallet
-testdict=$datadir/test100k.mallet.dict
-testdoccnt=100000
-testwordcnt=32733688
-alpha=0.5
-beta=0.1
+check_ret()
+{
+if [ "$?" -ne "0" ] ; then
+    echo "run command error, quit...."
+    exit -2
+fi
+}
 
-# ap-sample
-datadir=$homedir/data/ap-sample-mallet
-gibbsdict=$datadir/ap-sample.mallet.wordids
-harpdict=$datadir/ap-sample.mallet.wordids
-testset=$datadir/ap-sample.mallet.input
-testdict=$datadir/ap-sample.mallet.dict
-testdoccnt=2278
-testwordcnt=463468
-alpha=2.5
-beta=0.1
-
-CMD=$1
-shift
 
 help()
 {
 cat <<EOF
 lda-test commands: 
-
-  evaluate-harp       load the model from harp lda trainer and test likelihood on held-out testset
+  set-testset     <ap-sample | enwiki-100k> setup the testset 
+  evaluate-harp   <modeldir>    load the model from harp lda trainer and test likelihood on held-out testset
+  evaluate-mallet <modeldir>    load the model from mallet lda trainer and test likelihood on held-out testset
+  evaluate-gibbs  <modeldir>    load the model from gibbs lda trainer and test likelihood on held-out testset
 
 Include --help with any option for more information
 EOF
 }
 
+
+# dataset
+init()
+{
+    if [ "$TESTSET" == "enwiki-100k" ] ; then
+        # enwiki-100k
+        datadir=$homedir/data/enwiki-100k
+        gibbsdict=$datadir/enwiki-100k-gibbs.wordids
+        harpdict=$datadir/enwiki-100k-reid.wordids
+        testset=$datadir/test100k.mallet
+        testdict=$datadir/test100k.mallet.dict
+        testdoccnt=100000
+        testwordcnt=32733688
+        alpha=0.5
+        beta=0.1
+    elif [ "$TESTSET" == "ap-sample" ] ; then
+        # ap-sample
+        datadir=$homedir/data/ap-sample-mallet
+        gibbsdict=$datadir/ap-sample.mallet.wordids
+        harpdict=$datadir/ap-sample.mallet.wordids
+        testset=$datadir/ap-sample.mallet.input
+        testdict=$datadir/ap-sample.mallet.dict
+        testdoccnt=2278
+        testwordcnt=463468
+        alpha=2.5
+        beta=0.1
+    else
+        echo "testset '$TESTSET'=$TESTSET not found, quit..."
+        help
+        exit -2
+    fi
+}
+
+# start here
+
+CMD=$1
+shift
+
 CLASS=
 
 case $CMD in
-	evaluate-harp) 
-        # <harp model dir> <runid>
-        modeldir=$1
-        runid=$2
-        mkdir $runid
-        cd $runid
-        for d in `ls`; do python $homedir/src/preprocess/convertHarp2Mallet.py $d $alpha $beta $testdict $harpdict; done
-        cd ..
-        python $homedir/src/evaluation/test_likelihood.py $homedir/tool/mallet/bin/ harp $runid $testset $testdoccnt $testwordcnt
-
+    set-testset)
+        export TESTSET=$1
+        echo "sorry, you have to do it yourself by type this command in shell: "
+        echo 
+        echo "export TESTSET=$1"
+        echo 
+        exit 0
         ;;
-	evaluate-gibbs) 
-        # <gibbs model dir> <runid>
-        modeldir=$1
-        runid=$2
-        mkdir $runid
 
+    evaluate-harp) 
+        init
+        # <harp model dir> 
+        modeldir=$1
         savedir=`pwd`
         cd $modeldir
-        
-        phifiles=`ls *.phi`
-        betafiles=`ls *.beta`
+        for d in `ls`; do python $homedir/src/preprocess/convertHarp2Mallet.py $d $alpha $beta $testdict $harpdict; done
+
+        cd $savedir
+        python $homedir/src/evaluation/test_likelihood.py $homedir/tool/mallet/bin/ harp $modeldir $testset $testdoccnt $testwordcnt
+
+        ;;
+
+     evaluate-mallet) 
+        init
+        # <harp model dir>
+        modeldir=$1
+        savedir=`pwd`
+        cd $modeldir
+
+        malletfiles=`ls *.mallet 2>>/dev/null`
+        if [ "$?" -ne "0" ] ; then
+            modelfiles=`ls model.* 2>>/dev/null`
+            if [ "$?" -ne "0" ] ; then
+                echo "model. files not found, quit..."
+                exit -2
+            else
+                for f in $modelfiles; do mv $f $f.mallet; done
+            fi
+        fi
+
+        malletfiles=`ls *.mallet 2>>/dev/null`
+        if [ "$?" -eq "0" ] ; then
+            cd $savedir
+            python $homedir/src/evaluation/test_likelihood.py $homedir/tool/mallet/bin/ mallet $modeldir $testset $testdoccnt $testwordcnt
+            #check_ret
+        fi
+
+
+        ;;
+
+    evaluate-gibbs) 
+        init
+        # <gibbs model dir> 
+        modeldir=$1
+        savedir=`pwd`
+        cd $modeldir
+
+        phifiles=`ls *.phi 2>>/dev/null`
+        if [ "$?" -ne "0" ] ; then
+            echo ".phi files not found at $modeldir, quit...."
+            exit 2
+        fi
+
+        betafiles=`ls *.beta 2>>/dev/null`
         if [ "$?" -ne "0" ] ; then
             for f in $phifiles; do python $homedir/src/preprocess/convertGibbsPhiToBeta.py $f `basename $f .phi`.beta; done
         fi
 
 
-        betafiles=`ls *.beta`
-        harpfiles=`ls *.harp`
+        betafiles=`ls *.beta 2>>/dev/null`
+        harpfiles=`ls *.harp 2>>/dev/null`
         if [ "$?" -ne "0" ] ; then
             for f in $betafiles; do python $homedir/src/preprocess/convertBeta2Harp.py $f $harpdict $beta; done
         fi
 
-        harpfiles=`ls *.harp`
-        malletfiles=`ls *.mallet`
+        harpfiles=`ls *.harp 2>>/dev/null`
+        malletfiles=`ls *.mallet 2>>/dev/null`
         if [ "$?" -ne "0" ] ; then
             for f in $harpfiles; do python $homedir/src/preprocess/convertHarp2Mallet.py $f $alpha $beta $testdict $harpdict; done
         fi
@@ -87,12 +152,12 @@ case $CMD in
         python $homedir/src/evaluation/test_likelihood.py $homedir/tool/mallet/bin/ gibbs $modeldir $testset $testdoccnt $testwordcnt
 
         ;;
-	
-	run) 
+
+    run) 
         CLASS=$1
         shift
         python $CLASS $*
         ;;
-	*) echo "Unrecognized command: $CMD"; help; exit 1;;
+    *) echo "Unrecognized command: $CMD"; help; exit 1;;
 esac
 
